AWSTemplateFormatVersion: "2010-09-09"
Description: "My first template"
Parameters:
  Versioning:
    Type: String
    Default: Enabled
    AllowedValues:
      - Suspended
      - Enabled
  Name:
    Type: String
    Default: bem-bucket-demo123
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t3.micro
Resources:
  DemoBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref Name
      VersioningConfiguration: 
        Status: !Ref Versioning
      
  DemoSM:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MySecretInfo
      Description: "This secret has a dynamically generated secret password."
      GenerateSecretString:
        SecretStringTemplate: '{"username": "bem"}'
        GenerateStringKey: "password"
        PasswordLength: 10
        ExcludeCharacters: '"@/\'

  DemoEC2:
   Type: AWS::EC2::Instance
   Properties:
    InstanceType: !Ref InstanceType
    ImageId: "ami-02aead0a55359d6ec"

Outputs:
  BucketName:
    Description: My bucket name
    Value: !Ref DemoBucket
  InstancePublicIP:
    Description: My instance ip
    Value: !GetAtt
      - DemoEC2
      - PublicIp